### PR TITLE
build: add node v16 & update Github actions

### PR DESCRIPTION
**Pull request by amareshsm**
## Description

1. Add node v16 to workflow.
2. update Github actions to v3.

### CODE REVIEW

**Comment by valscion** [comment]
Can we keep the existing Node.js version 10 tests as they were?

**Comment by valscion** [comment]
Hi @amareshsm are you still working on this PR or is it stale?

**Comment by amareshsm** [comment]
> Can we keep the existing Node.js version 10 tests as they were?

done. pls, approve the workflow.

**Comment by valscion** [comment]
Thanks, I did that! I'll try to remember to check this PR tomorrow when I'm back at the computer ☺️

**Comment by valscion** [comment]
Huh, v18.x seems to be failing and I have no clue why:

```
 [13:47:42] 'compileViewerScripts' errored after 1.63 s
[13:47:42] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
    at NormalModule._initBuildHash (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/NormalModule.js:867:17)
    at handleParseResult (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/NormalModule.js:933:10)
    at /home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/NormalModule.js:1025:4
    at processResult (/home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/NormalModule.js:742:11)
    at /home/runner/work/webpack-bundle-analyzer/webpack-bundle-analyzer/node_modules/webpack/lib/NormalModule.js:806:5
[13:47:42] 'build' errored after 2.74 s
Error: Process completed with exit code 1.
```

**Review by valscion — APPROVED** [review]
Thanks for the PR! I'll merge this now.

I want to get the Node.js v16.x and the other changes in as they work, so I dropped the addition of Node.js v18.x now.

If you can take a look at figuring out why the tests fail with Node.js v18.x, that'd be super!

**Pull request merged**
