### PR TITLE
Fix webpack 4 warning

### LINKED ISSUE #154: Webpack 4 outputs deprecation warnings
#### Issue description

Using `webpack-bundle-analyzer` with Webpack 4:

```
DepreciationWarning: Tappable.plugin is deprecated. Use new API on `.hooks` instead
```

#### Technical info
* Webpack Bundle Analyzer version: 2.10.0
* Webpack version: Webpack 4.0.0-beta.2
* Node.js version: 9
* npm/yarn version: 1.3.2
* OS: Linux

#### Debug info

How do you use this module? As CLI utility or as plugin?

Plugin inside [Size Limit](https://github.com/ai/size-limit/)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

```
      openAnalyzer: true,
      analyzerMode: 'server',
      defaultSizes: 'gzip'
```

What other Webpack plugins were used?

`compression-webpack-plugin` and `uglifyjs-webpack-plugin`

Related issue: https://github.com/ai/size-limit/pull/42

### PR DESCRIPTION
**Pull request by ai**
Fix #154 according to @sokra suggestion

### CODE REVIEW

**Comment by valscion** [comment]
Thanks, this looks good to me! Were you able to check that this fixes https://github.com/ai/size-limit/pull/42 warning being displayed, and that things still work with webpack 4?

**Comment by ai** [comment]
@valscion I still have a warning because 2 other plugins use old API :(. It is the long way :D.

**Comment by ai** [comment]
@valscion Travis CI is broken because of timeout :)

**Comment by ai** [comment]
I sent PR to `uglify-webpack-plugin` and `compression-webpack-plugin` as well. With all this 3 PRs Size Limit doesn’t show any warnings and work perfectly.

**Comment by valscion** [comment]
Super awesome, thank you! This looks good to me :+1:. I added a changelog entry and will soon merge this once tests pass and then release a new patch version.

**Comment by valscion** [comment]
Released in v2.10.1 :relaxed:

**Pull request merged**
