### PR TITLE
Add leading zero to hour & minute on <title /> when needed

### PR DESCRIPTION
**Pull request by mhxbe**
Hi, 

Recently @gaokun requested/added a date in the <title /> tag which is a great addition to the tool.
Last night, when I was using webpack-bundle-analyzer on a personal project, I saw the following date:
```
<title>react-starter [21 Sep 2019 at 1:5]</title>
```

**Problem**
By default, `.getHours()` & `.getMinutes()` return a number which results in a one-digit for all numbers lower than 10. In this case, it's displaying **1:5** for the hour & minutes whereas **01:05** would be nicer. 

**Possible solution**
Adding a leading zero in combination with converting it to a String, leverages us the usage of `.slice(-2)` so it returns the last 2 digits. 

Another solution is the usage of .substr(-2) but it seems this method will be deprecated in the future
Source for `.slice()`: [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)
Source for `.substr()`: [String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)

If there are better approaches, I'm open for them.

**Examples**
You can copy paste the following code-snippet in your browser console to see it in action.
``` 
const someDate = new Date('2019-09-21 01:05');

console.log('Hours:', someDate.getHours());
console.log('Minutes:', someDate.getMinutes());

console.log('With leading zeros:');
console.log('Hours:', `0${someDate.getHours()}`.slice(-2));
console.log('Minutes:', `0${someDate.getMinutes()}`.slice(-2));
```

### CODE REVIEW

**Comment by gaokun** [comment]
Thanks for mention this. It is nice format to read.

And what about ES6 `padStart` function?

```js
'4'.padStart(2, 0);  //  result: '04'
```

In this case, they are both OK, anyway.

**Comment by mhxbe** [comment]
That's even better and much cleaner, thanks for the suggestion.

I quickly checked the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Specifications) and they state that `.padStart()` is part of ES2017.
This means it's covered with `@babel/present-env` but there's a possible catch: IE11-support.

Is it safe to say this will work in both cases (server & client) since [src/viewer.js](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/src/viewer.js) is 'server-side' code thus not affecting IE11?

**Comment by th0r** [comment]
We doesn't support IE11 in client bundle so it's completely safe to use padStart.

**Comment by mhxbe** [comment]
Ok, thanks for the quick response @th0r.

I've pushed another commit where I used template literals to convert the number to a String.
```
const hour = `${time.getHours()}`.padStart(2,0);
const minute = `${time.getMinutes()}`.padStart(2,0);
```

I can change this to the following if preferred:
```
const hour = time.getHours().toString().padStart(2,0);
const minute = time.getMinutes().toString().padStart(2,0);
```

**Comment by th0r** [comment]
Tag templates are ok, but let's better change method calls to `padStart(2, '0')` to be more clear.

**Comment by th0r** [comment]
According to tests, `padStart` is not available in Node v6. 😕
I don't want to add another runtime dependency to polyfill it so let's better use `slice` approach.

**Comment by valscion** [comment]
Hi @mhxbe, it would be great to get this bug fixed :relaxed:. Are you still up for this PR?

**Comment by mhxbe** [comment]
Hi @valscion, I've been busy past week(s) but I will get this fixed tonight.
It's possible I'll reopen a new PR because I've made some 'polluted' commits. 

If you've got time to fix this now, feel free to open up a new PR with [the fix](https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/314/commits/27b2de0d4a4334ccfdc2a44424984c563f39d06d). I'll happily close this one then. If this is not the case, I will fix this tonight.

**Comment by valscion** [comment]
Ok this seems good to go to me! Thanks :relaxed: I'll merge once CI is green

**Pull request merged**
