### PR TITLE
Drop lodash from the package

### PR DESCRIPTION
**Pull request by TrySound**
Lodash is quite big package and often overused for things available
natively. In this diff I removed it from package dependencies and left
only for tests.

### CODE REVIEW

**Comment by th0r** [comment]
Thanks for the PR, but I don't want to drop lodash as JS std library is not good enough to replace it yet and code becomes more complex.

**Comment by TrySound** [comment]
Well, I spent a lot of time digging through not very obvious lodash solutions.

**Comment by TrySound** [comment]
Also really in most cases it's just each -> forEach, filter -> filter, map -> map. Are these cases are less obvious?

**Comment by TrySound** [comment]
Ok. Let's step away from code complication and I will do only drop in replacement.

**Comment by onigoetz** [comment]
Hi, I'm a bit late to the party, is this PR still in progress ?

I'm also trying to remove lodash from my dependencies and would help reduce the install size of my tools.

**Pull request closed without merging**
