### PR TITLE
Fix .cjs files not showing up in bundle analyzer

### PR DESCRIPTION
**Pull request by Rush**
I compile my server-side code to .cjs files. I was surprised to find the bundle analyzer view to be completely empty.

After debugging it turned out that .cjs filename was not being handled.

I think in general all assets should be included in the analysis but .cjs is good for now!

Could you release this patch on npm as well?

### CODE REVIEW

**Comment by Rush** [comment]
Btw. I signed CLA. You can re-run your CI.

**Review by snitin315 — APPROVED** [review]
LGTM

**Comment by Rush** [comment]
Thanks! :) I would appreciate if it could be released in the nearby future.

**Comment by valscion** [comment]
Looks good, thanks! Are you able to create a small test to verify this won't regress in the future? Also a mention of this change in changelog would be nice 😊

**Comment by valscion** [comment]
Hi @Rush are you still interested in getting this PR done? We'd need this PR to be rebased on top of latest `master` and a small test added to verify it won't regress in the future. A changelog entry would also be nice.

**Review by ShenHongFei — APPROVED** [review]

**Comment by alexander-akait** [comment]
@valscion Hello, can we resolve this PR? Because a got a lot of questions why `.cjs` doesn't work

**Comment by valscion** [comment]
Yeah a PR which adds a minimal test case showing that .cjs files work, adds a changelog entry and does this same change will be accepted.

**Comment by alexander-akait** [comment]
Okey, I will resend it :+1:

**Comment by Rush** [comment]
Sorry I don't have any bandwidth to work on it. One solution to consider would be to merge this and create a follow up issue with a test case. I've been using my .cjs branch for almost two years now :-)

**Comment by valscion** [comment]
Yeah now that this PR is up-to-date then adding some test coverage should hopefully be quite simple.

Would you @Rush have bandwidth to create a changelog entry for this change still?

**Comment by alexander-akait** [comment]
@valscion Added a test case

**Review by valscion — APPROVED** [review]
Looks great, thanks!

**Comment by valscion** [comment]
This has now been released as part of v4.10.2

**Pull request merged**
