### PR TITLE
Fix missing child bundles throwing an error

### PR DESCRIPTION
**Pull request by dabbott**
This fixes an issue introduced in https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/376, where `getChildAssetBundles` sometimes doesn't find the given `statAsset.name` and returns undefined, which later causes an error.

This probably isn't a great fix, and I'm not sure specifically how to reproduce the issue, but it seems harmless enough that I'll be using it for now at least 😅

### CODE REVIEW

**Comment by dabbott** [comment]
@jsf-clabot rerun

**Comment by valscion** [comment]
Thanks! Would you be able to setup a test with `stats.json` that breaks, similar to files in here? https://github.com/webpack-contrib/webpack-bundle-analyzer/tree/master/test/stats

Those files are used by tests defined in https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/test/analyzer.js

**Review by th0r — CHANGES_REQUESTED** [review]
@valscion let's not merge it without a test please.

**Comment by valscion** [comment]
> @valscion let's not merge it without a test please.

:+1: sounds good to me!

**Comment by masterkidan** [comment]
@dabbott : It would be great if you can debug a bit deeper, my understanding is that we eliminate assets generated by plugins like HtmlWebpackPlugin in the regex/assetfilter (only js assets are analyzed). It looks like in your webpack config something with HtmlWebpackPlugin is generating js assets, can you share the config so I can understand the issue a bit better?

**Comment by dabbott** [comment]
@masterkidan Thanks for checking this out. Here's my webpack config: https://github.com/dabbott/react-native-web-player/blob/58e49839516a32a91267510b550823e644b72364/webpack/webpack.config.js. 

If you'd like, you should be able to pull down that `react-native-web-player/webpack-bundle-analyzer` branch and run `yarn build` to see the error (if you have `webpack-bundle-analyzer` linked locally so you're pointing to master). I don't know how webpack assets are organized _at all_ really, so I probably won't be much help in making a better fix, but if you have suggestions or a fix to test I can definitely try it out.

**Comment by masterkidan** [comment]
@dabbott : I think this may be because of the fact your template is an 'ejs' file. This is not something that gets filtered out by the regex, but the template compilation is a child compilation, I think a slightly better way would be to check why
// Picking only `*.js or *.mjs` assets from bundle that has non-empty `chunks` array
  bundleStats.assets = _.filter(bundleStats.assets, asset => {
    // Removing query part from filename (yes, somebody uses it for some reason and Webpack supports it)
    // See #22
    asset.name = asset.name.replace(FILENAME_QUERY_REGEXP, '');

    return FILENAME_EXTENSIONS.test(asset.name) && !_.isEmpty(asset.chunks) && isAssetIncluded(asset.name);
  });
is not filtering out the asset, and fix it here instead :) . 

You can use https://github.com/masterkidan/worker-loader-no-stats as a base and add a simple index.ejs template with a WebpackHtlmPlugin to process it.... I am not sure when I will be able to get to it on my own.

**Comment by dabbott** [comment]
Ok! I was able to track this down. This happens when workers contain dynamic imports with `import('./some-dep.js')`. I added a test case (generated via https://github.com/dabbott/worker-loader-dynamic-imports).

I think this is probably in an OK state to merge, and @masterkidan if you have time you could do a better fix in the future.

**Comment by th0r** [comment]
@dabbott so, what is the actual reason for the exception? What asset it tries to find but it's not there?

**Comment by dabbott** [comment]
We're looking for `"1.bundle.worker.js"` as `assetName` in:

```
function getChildAssetBundles(bundleStats, assetName) {
  return _.find(bundleStats.children, (c) =>
    _(c.assetsByChunkName)
      .values()
      .flatten()
      .includes(assetName)
  );
}
```

That name doesn't exist in `assetsByChunkName`. (Maybe cause it's not a named chunk? It does exist in `c.chunks` I believe)

**Pull request merged**
