### PR TITLE
Disable viewer websocket connection if mode is static

### LINKED ISSUE #195: Websocket Connection blocked when serving over HTTPS
The opened WebSocket connection is always `ws:`. If the file is served via HTTPS, this should be `wss:` or else the browser will block the connection.

Message from Chrome:

    bundle-report.html:formatted:967 Mixed Content: The page at 'https://foo.bar/bundle-report.html'
    was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://foo.
    bar/'. This request has been blocked; this endpoint must be available over WSS.

The culprit is here, probably:
https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/2c0555536e215c8096ed6f7d10b1e5783251f76a/client/viewer.jsx#L11

### PR DESCRIPTION
**Pull request by sebastianhaeni**
Resolves #195

### CODE REVIEW

**Comment by valscion** [comment]
Looks good to me. What do you think, @th0r?

**Comment by th0r** [comment]
Looks good. Thanks @sebastianhaeni!
@valscion could you publish a new version with this change because I don't have time right now?

**Comment by valscion** [comment]
>  @valscion could you publish a new version with this change because I don't have time right now?

Will do :+1:

**Comment by valscion** [comment]
Published v3.0.3 with this change :tada:

**Pull request merged**
