### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by th0r**

### CODE REVIEW

**Comment by th0r** [comment]
@valscion Could you check this PR please?

**Comment by valscion** [comment]
Yeah I'll check this soon. I might not get to it today as I am home sick and don't have much energy due to a fever :(

**Comment by th0r** [comment]
Ok, @valscion, I've well-tested it and it looks fine. I'll merge it.

**Comment by valscion** [comment]
Yeah sorry, influenza has got the best of me and I am still recovering. I'm happy that you asked for me to review, thanks :)

**Comment by valscion** [comment]
Ok I was able to look at this now. It looks good as far as I can see — I don't know much about gulp, but the new gulpfile does look much simpler now. Thanks!

**Pull request merged**
