### PR TITLE
Fix handling of webpack array configs

### PR DESCRIPTION
**Pull request by ctavan**
When trying to analyze a stats.json for a webpack bundle generated off
of an array webpack.config.json webpack-bundle-analyzer was throwing:

Could't analyze webpack bundle:
TypeError: Cannot read property 'assets' of undefined

This bug was probably introduced in
https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/376

Example webpack config to generate a stats.json file that causes the
crash:

```js
function getConfig({ config }) {
  return {
    mode: 'production',
    entry: './src/index.js',
    performance: {
      hints: 'warning',
    },
    optimization: {
      minimize: true,
    },
    output: {
      filename: `${config}-[name].js`,
      chunkFilename: `${config}-chunk-[name].js`,
      path: `${__dirname}/`,
    },
  };
}

module.exports = [{ config: 'config-1' }, { config: 'config-2' }].map(getConfig);
```

### CODE REVIEW

**Comment by valscion** [comment]
This looks good to me, thank you!

I'll merge once Travis CI happens to work again.

**Comment by valscion** [comment]
Can you add a changelog entry?

**Comment by ctavan** [comment]
> Can you add a changelog entry?

Done!

**Comment by valscion** [comment]
Thanks!

**Comment by valscion** [comment]
Released in v4.2.0 :relaxed:. Thank you for your contributions!

**Pull request merged**
