### PR TITLE
chore: update md

### PR DESCRIPTION
**Pull request by PengBoUESTC**
update introduction of `analyzerPort` option

### CODE REVIEW

**Comment by valscion** [comment]
Thanks, looks good to me! Can you sign the CLA?

**Comment by PengBoUESTC** [comment]
> Looks like your original commit used some email that isn't tied to your GitHub account so GitHub and thus EasyCLA isn't able to link them together.
> 
> chore__update_md_·_webpack-contrib_webpack-bundle-analyzer_84d4c15
> 
> https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

I register CLA just now, how to deal with that

**Comment by valscion** [comment]
If you've configured your local git client now properly then the easiest way to solve this might be to start fresh with a new pull request and new commits.

**Comment by valscion** [comment]
I retriggered the CLA authorization but it didn't pass

**Pull request closed without merging**
