### PR TITLE
Collect modules from `chunks` array

### LINKED ISSUE #174: After migration to Angular 6 stats analyzer does not show full information
#### Issue description
I have migrated to Angular 6 and cannot see detailed info like it was the case with Angular 5
...

#### Technical info
* Webpack Bundle Analyzer version: 2.11.1
* Webpack version: 4.6.0
* Node.js version: 9.8.0
* npm/yarn version: 5.6.0
* OS: Windows 10

#### Debug info
As a CLI. I am running command `ng build --prod --stats-json`

What other Webpack plugins were used? No, At least Angular CLI uses something under the hood

[stats.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1986968/stats.zip)

### PR DESCRIPTION
**Pull request by th0r**
Fixes #174

### CODE REVIEW

**Comment by th0r** [comment]
> Huh, I wonder what has caused webpack to start outputting such stats JSON

I've upgraded out work project to webpack 4 recently and didn't notice any change in stats file format. Seems like angular guys post-process it in some way...

**Comment by valscion** [comment]
Yeah, I think I've seen a few issues that have had trouble with angular CLI output. This might fix them.

**Comment by vytautas-pranskunas-** [comment]
I see you have found an issue. When it is available in npm?

**Comment by valscion** [comment]
We'll let you know when we publish a version with this fix. Usually we do it quite soon after fixing issues.

**Pull request merged**
