### PR TITLE
replace <str>.length with Buffer.byteLength(<str>)

### PR DESCRIPTION
**Pull request by hulkish**
Some chars represent a byte length greater than 1. This means string length could report incorrect `parsedSize`, for bundles - if any special chars are used. More on this [here](https://sankhs.com/2016/03/17/content-length-http-headers/).

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Looks legit, do you think you could add an auto test to cover this case?

**Comment by hulkish** [comment]
@valscion can you point me in the right direction for this? Im trying to get an idea of how i am intended to generate the fixture for this test?

**Comment by valscion** [comment]
The best bet might be to create a small reproduction repository with plain webpack and generate a stats.json object and output bundle from there. Supply that output to the basis of your new test and test that the expected sizes match what you want.

**Comment by hulkish** [comment]
@valscion that makes sense, thank you. 

I guess I was looking for a script that creates one for me, or something lol

**Comment by hulkish** [comment]
@valscion @EugeneHlushko will this do it?

**Comment by th0r** [comment]
@hulkish thanks, merged!

**Pull request merged**
