### PR TITLE
Add support for 'auto' option with analyzer port #281

### LINKED ISSUE #281: Convert `analyzerPort: "auto"` option to `analyzerPort: 0`
Currently to use automatic port selection one should use `analyzerPort: 0` option.
Despite the face that it's a value from a native Node.js API it's a little non intuitive.
We can introduce an alias: `analyzerPort: "auto"` and replace it with `0` before passing to http server.

TODO:
- Add alias
- Document it

### PR DESCRIPTION
**Pull request by avin-kavish**
It's a single line of quite self-explanatory code. But I'm happy to write tests, just not sure where.

The logic I went with was, if analyzer port is specified, (and) if it is 'auto' use 0, else use the specified value. If it is not specified, use 8888, the default.

Closes #281

### CODE REVIEW

**Comment by avin-kavish** [comment]
`"before each" hook for "should support stats files with all the information in `children` array":`

Some issue with nightmare I think. Tests run fine on my pc

**Comment by th0r** [comment]
Can we support `auto` value for CLI `--port` option as well?

**Comment by th0r** [comment]
Could you please also update [this section in readme](https://github.com/webpack-contrib/webpack-bundle-analyzer#options)?

**Comment by avin-kavish** [comment]
Sorry about the delay, I had some projects to work on. Not sure if you got the notification, I've force pushed to keep the commit history clean.

**Comment by th0r** [comment]
Everything is fine except some issue with the build on CI. Could you take a look at why it fails?

**Comment by th0r** [comment]
@avin-kavish Thanks for the PR, merged!

**Comment by th0r** [comment]
Published in `v3.4.0`

**Pull request merged**
