### PR TITLE
Fix parsing webpack 4's chunks

### PR DESCRIPTION
**Pull request by jdelStrother**
Webpack 4 has a new chunk loading style, looking something like this:

```js
(window.webpackJsonp=window.webpackJsonp||[]).push([[27],{"57iH":function(e,n,t){console.log("hello world")}}]);
```

WDYT to this approach?

### CODE REVIEW

**Comment by valscion** [comment]
Hi, and welcome! Thank you for your PR :relaxed:

I was wondering, is there any case where the "minimum ID" is needed? The `[27]` part in your example. Is there a way for webpack 4 to generate numerical IDs instead of these modules keyed by a hash of some sort?

This PR in itself looks great! Would you be open to checking whether there's new sorts of chunk loading styles that also start with the `(window.webpackJsonp=window.webpackJsonp||[]).push` approach? Something similar to this:

* Extra bundle with modules inside Array concat: [bundle](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/test/bundles/validExtraBundleWithModulesInsideArrayConcat.js) -> [parsed modules](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/test/bundles/validExtraBundleWithModulesInsideArrayConcat.modules.json)
* JSONP with Array concat and entry point: [bundle](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/test/bundles/validJsonpWithArrayConcatAndEntryPoint.js) -> [parsed modules](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/test/bundles/validJsonpWithArrayConcatAndEntryPoint.modules.json)

As you can see in the above example, the module IDs are affected by the ID in the first parameter.

Figuring this out can be done outside of this PR, though — this can go in on itself.

Could you create a changelog entry to CHANGELOG.md and link back to this PR, similarly to how the links have been done in v2.10.0 and above?

**Comment by jdelStrother** [comment]
> I was wondering, is there any case where the "minimum ID" is needed? The [27] part in your example. Is there a way for webpack 4 to generate numerical IDs instead of these modules keyed by a hash of some sort?

Yeah, re-reading it, the minimum id isn't necessary to calculate the ids in the chunk, so it's misleadingly named.   I'll change it.

> Would you be open to checking whether there's new sorts of chunk loading styles

The only place where I could find webpackJsonp being used is here - https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkTemplatePlugin.js.  There's an optional third argument (`entries`), which happens to work ok with my original code, but I'll add a test to confirm it.

> Could you create a changelog entry to CHANGELOG.md and link back to this PR

will do

**Comment by valscion** [comment]
> The only place where I could find webpackJsonp being used is here - https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkTemplatePlugin.js. There's an optional third argument (entries), which happens to work ok with my original code, but I'll add a test to confirm it.

:+1:

I'll add a non-master link to the file in question so it won't get lost if files are moved around as webpack is developed: https://github.com/webpack/webpack/blob/v4.0.1/lib/web/JsonpChunkTemplatePlugin.js

**Comment by valscion** [comment]
Looks great! Thank you for contributing! :tada:

**Comment by valscion** [comment]
Released in v2.11.1 :tada:

**Pull request merged**
